[package]
name = "kernel"
version = "0.1.0"
authors = ["Gaelan Steele <gbs@canishe.com>, Tavi Kohn <tavi.kohn@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
bit_field = "0.9"
bitflags = "1.0"
linked_list_allocator = "0.5"
lazy_static = {version = "0.2", features = ["spin_no_std"]}
once = "0.3"
multiboot2 = "0.3"
rlibc = "1.0"
spin = "0.4"
volatile = "0.2"
x86_64 = "0.1"