[package]
name = "kernel"
version = "0.1.0"
authors = ["Gaelan Steele <gbs@canishe.com>, Tavi Kohn <tavi.kohn@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
volatile = "0.2.3"
spin = "0.4.5"
multiboot2 = "0.1.0"