[package]
name = "kernel"
version = "0.1.0"
authors = ["Gaelan Steele <gbs@canishe.com>, Tavi Kohn <tavi.kohn@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
bitflags = "1.0"
once = "0.3"
multiboot2 = "0.3"
rlibc = "1.0"
spin = "0.4"
volatile = "0.2"
x86_64 = "0.1"